/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FilmMagic;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author snake
 */
public class MantenimientoVideoJ extends javax.swing.JInternalFrame {

    /**
     * Creates new form MantenimientoVideoJ
     */
    public MantenimientoVideoJ() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTipoVJ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtExisVJ = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEstatusVJ = new javax.swing.JTextField();
        txtCodigoVJ = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreVJ = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtClasiVJ = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        label_status = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        registro = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(true);

        jLabel5.setText("Existencia VideoJuego");

        jLabel6.setText("Estatus de VideoJuego");

        jLabel1.setText("Codigo VideoJuego");

        jLabel2.setText("Nombre VideoJuego");

        jLabel3.setText("Clasificacion VideoJuego");

        jLabel4.setText("Tipo de VideoJuego");

        jLabel8.setText("Ingresar Codigo VideoJuego");

        registro.setText("REGISTRO");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });

        eliminar.setText("ELIMINAR");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoVJ, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreVJ))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstatusVJ)
                            .addComponent(txtExisVJ)
                            .addComponent(txtTipoVJ)
                            .addComponent(txtClasiVJ))))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(registro))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(modificar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buscar)
                                        .addGap(2, 2, 2)))))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_buscar)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(eliminar)
                                .addGap(24, 24, 24)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registro)
                        .addGap(34, 34, 34)
                        .addComponent(eliminar)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(modificar)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(label_status, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoVJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombreVJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtClasiVJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtTipoVJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtExisVJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEstatusVJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/labfm", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into videojuegos values(?,?,?,?,?,?,?)");
            pst.setString(1, "0");
            pst.setString(2, txtCodigoVJ.getText().trim());
            pst.setString(3, txtNombreVJ.getText().trim());
            pst.setString(4, txtClasiVJ.getText().trim());
            pst.setString(5, txtTipoVJ.getText().trim());
            pst.setString(6, txtExisVJ.getText().trim());
            pst.setString(7, txtEstatusVJ.getText().trim());
            pst.executeUpdate();
            txtCodigoVJ.setText("");
            txtNombreVJ.setText("");
            txtClasiVJ.setText("");
            txtTipoVJ.setText("");
            txtExisVJ.setText("");
            txtEstatusVJ.setText("");
            label_status.setText("Registro exitoso.");
            {
                JOptionPane.showMessageDialog(null, "Registro Exitosamente VideoJuego.");
            }
        }catch (Exception e){

        }
    }//GEN-LAST:event_registroActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        //Codigo que permite borrar registros en la base de datos
        try {
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/labfm", "root", "");
            PreparedStatement pst = cn.prepareStatement("delete from videojuegos where CodigoVideoJ = ?");

            pst.setString(1, txt_buscar.getText().trim());
            pst.executeUpdate();

            txtCodigoVJ.setText("");
            txtNombreVJ.setText("");
            txtClasiVJ.setText("");
            txtTipoVJ.setText("");
            txtExisVJ.setText("");
            txtEstatusVJ.setText("");
            label_status.setText("Registro eliminado.");
            {
                JOptionPane.showMessageDialog(null, "VideoJuego Registro Eliminado.");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        //Codigo que permite actualizar registros en la base de datos
        try {
            String ID = txt_buscar.getText().trim();

            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/labfm", "root", "");
            PreparedStatement pst = cn.prepareStatement("update videojuegos set CodigoVideoJ = ?, NombreVideoJ = ?, ConsolaVideoJ = ?, TipoVideoJ = ?, ExistenciaVideoJ = ?, EstatusVideoJ = ? where ID = " + ID);

            pst.setString(1, "0");
            pst.setString(1, txtCodigoVJ.getText().trim());
            pst.setString(2, txtNombreVJ.getText().trim());
            pst.setString(3, txtClasiVJ.getText().trim());
            pst.setString(4, txtTipoVJ.getText().trim());
            pst.setString(5, txtExisVJ.getText().trim());
            pst.setString(6, txtEstatusVJ.getText().trim());
            pst.executeUpdate();

            label_status.setText("Modificación exitosa.");
            {
                JOptionPane.showMessageDialog(null, "VideoJuego Actualizado Exitosamente.");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        //Codigo que permite consultar registros en la base de datos
        try{
            Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/labfm", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from videojuegos where ID = ?");
            pst.setString(1, txt_buscar.getText().trim());

            ResultSet rs = pst.executeQuery();

            if(rs.next()){
                txtCodigoVJ.setText(rs.getString("CodigoVideoJ"));
                txtNombreVJ.setText(rs.getString("NombreVideoJ"));
                txtClasiVJ.setText(rs.getString("ConsolaVideoJ"));
                txtTipoVJ.setText(rs.getString("TipoVideoJ"));
                txtExisVJ.setText(rs.getString("ExistenciaVideoJ"));
                txtEstatusVJ.setText(rs.getString("EstatusVideoJ"));
            } else {
                JOptionPane.showMessageDialog(null, "VideoJuego no Registrado.");
            }

        }catch (Exception e){

        }
    }//GEN-LAST:event_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel label_status;
    private javax.swing.JButton modificar;
    private javax.swing.JButton registro;
    private javax.swing.JTextField txtClasiVJ;
    private javax.swing.JTextField txtCodigoVJ;
    private javax.swing.JTextField txtEstatusVJ;
    private javax.swing.JTextField txtExisVJ;
    private javax.swing.JTextField txtNombreVJ;
    private javax.swing.JTextField txtTipoVJ;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
